[package]
name = "zenbook-duo-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
evdev-rs = "0.6.3"
futures-lite = "2.6.1"
inotify = "0.11.0"
log = "0.4.29"
nusb = "0.2.1"
